server:
   port: 8094
spring:
  application:
    name: mcsv-ForoUsuarios
  datasource:
    driver-class-name: com.posgreesql.Driver
    url: jdbc:postgresql://localhost:5432/Foro
    username: root
    password: root1234
  jpa:
     hibernate:
       ddl-auto: create
     database: postgresql
     database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
      - optional:configserver:http://localhost:8888
      
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka