server:
  port: 8761
  
spring:
  application:
    name: mscv-Eureka
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    compatibility-verifier:
      compatible-boot-versions:
      - 3.2.4
    
eureka:
  instance:
     hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone:
        http://localhost:${server.port}/eureka/
